### ISSUE TITLE
Question for Kan-Polar Parameter Settings

### ISSUE THREAD

**Issue by huhanyu** [mpoluektov/kan-polar#2]
I have a question regarding the buildKA_init function from the kan-polar library. This function initializes the model with parameters m, n, q, p, ymin, and ymax. I would like to know if there are any recommended best practices or guidelines for setting these parameters, especially m, n, q, and p.

Additionally, I am interested in approximating a specific function, such as the Ackley function. How should I determine the appropriate values for ymin and ymax in this case? Are there any general rules or heuristics that can help me choose these bounds for effective function approximation?

I appreciate any insights or experiences shared by the community on this topic. Thank you!

**Comment by huhanyu** [comment]
@mpoluektov

**Comment by mpoluektov** [comment]
Hi @huhanyu 
Thanks for using my implementation of KANs!
You can see how I define the parameters for the test example in the `mainTraing.m` file. There you will also see the summary of the description of each parameter.
Parameter `m` is the number of the inputs (the number of components of the input vector), so it is exactly defined.
Parameter `p` is the number of the blocks (equal to the number of the outer functions). The classical case (Kolmogorov's proof) is to use `p=2*m+1`. However, we found out that sometimes smaller or larger number works better.
Parameters `n` and `q` are the numbers of the basis functions for the inner and the outer functions, respectively. I am afraid that there is no better way than to use training and validation datasets - use the first one to fit the model and the second one to measure the RMSE (standard ML approach to avoid overfitting). Doing this for different values of `n` and `q` should give the optimal values. When you use splines, these parameters must not be less than 4, so that may be a good starting point. If you have very large datasets, these parameters can also be large.
Regarding `ymin` and `ymax` - they are the lower and the upper limits of the output. I would just take your dataset and do `min(y)` and `max(y)` in MATLAB, if `y` is the column of your output values. This can be an approximate way to guess them and a good starting point. Keep in mind that if your dataset is experimental, then there may be outliers (errors) and such min/max operations will give very bad estimates ruining the model's performance.

**Comment by huhanyu** [comment]
Thanks for your awsome implementation of KANs!@mpoluektov When should I use the NK or GK method? In your example, GK runs faster, but sometimes the NK method trains the model faster. What causes this?

**Comment by huhanyu** [comment]
@mpoluektov

**Comment by mpoluektov** [comment]
You are welcome @huhanyu 
I am glad that researchers find it useful. 
My personal default choice is to use NK method. In the paper (link in README), we have shown that the GN method is much more sensitive to the initial guess. To be fair, we picked a challenging example for it, but nevertheless, it simply did not converge in many more cases than NK on that example. Furthermore, since the training problem is ill-posed (see again our paper), GN cannot be used straightforwardly and requires ridge (Tikhonov) regularisation. It is not a problem as such, but you have one more parameter `lam` to fine-tune. The performance of the methods very much depends on numerical parameters `lam` and `mu` for GN and only on `mu` for NK.

**Comment by huhanyu** [comment]
thanks for your kindly answer again! i got it.
